"""
Email Agent — sends BI reports and insights via email (SMTP/Gmail).
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

load_dotenv()

DEMO_MODE = os.getenv("DEMO_MODE", "false").lower() == "true"
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_EMAIL = os.getenv("SMTP_EMAIL", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")


def send_report_email(
    to_emails: list[str],
    subject: str,
    question: str,
    explanation: str,
    sql: str,
    source_name: str,
    chart_html: str = "",
    attachment_path: str = "",
) -> tuple[bool, str]:
    """
    Send a BI insight report via email.

    Returns:
        (success: bool, message: str)
    """
    if DEMO_MODE:
        return True, f"📧 [DEMO] Email would be sent to: {', '.join(to_emails)}"

    if not SMTP_EMAIL or not SMTP_PASSWORD:
        return False, "Email not configured. Set SMTP_EMAIL and SMTP_PASSWORD in .env"

    try:
        msg = MIMEMultipart("alternative")
        msg["From"] = SMTP_EMAIL
        msg["To"] = ", ".join(to_emails)
        msg["Subject"] = subject

        html_body = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f4f5f7; padding: 20px; }}
                .container {{ max-width: 640px; margin: auto; background: white; border-radius: 12px;
                              box-shadow: 0 2px 8px rgba(0,0,0,0.08); overflow: hidden; }}
                .header {{ background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white;
                           padding: 24px 28px; }}
                .header h1 {{ margin: 0; font-size: 20px; font-weight: 600; }}
                .header p {{ margin: 4px 0 0; font-size: 13px; opacity: 0.85; }}
                .body {{ padding: 24px 28px; }}
                .label {{ font-size: 11px; font-weight: 700; color: #6366f1; text-transform: uppercase;
                          letter-spacing: 0.06em; margin-bottom: 6px; }}
                .question {{ background: #f0f0ff; padding: 12px 16px; border-radius: 8px;
                             font-size: 14px; color: #333; margin-bottom: 20px; }}
                .explanation {{ font-size: 14px; color: #444; line-height: 1.7; margin-bottom: 20px; }}
                .sql-block {{ background: #1e1e2e; color: #a5b4fc; padding: 14px 18px;
                              border-radius: 8px; font-family: 'Courier New', monospace;
                              font-size: 12px; white-space: pre-wrap; margin-bottom: 20px; }}
                .footer {{ background: #f8f9fa; padding: 16px 28px; font-size: 11px;
                           color: #888; text-align: center; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🤖 Agentic BI Report</h1>
                    <p>Source: {source_name}</p>
                </div>
                <div class="body">
                    <div class="label">Question</div>
                    <div class="question">{question}</div>

                    <div class="label">AI Analysis</div>
                    <div class="explanation">{explanation}</div>

                    <div class="label">Generated SQL</div>
                    <div class="sql-block">{sql}</div>

                    {f'<div class="label">Chart</div>{chart_html}' if chart_html else ''}
                </div>
                <div class="footer">
                    Generated by Agentic BI Assistant · Powered by Vertex AI + BigQuery
                </div>
            </div>
        </body>
        </html>
        """

        msg.attach(MIMEText(html_body, "html"))

        # Attach file if provided
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header("Content-Disposition", f"attachment; filename={os.path.basename(attachment_path)}")
                msg.attach(part)

        # Send
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.send_message(msg)

        return True, f"✅ Email sent to: {', '.join(to_emails)}"

    except Exception as e:
        return False, f"❌ Email failed: {str(e)}"
